### ISSUE TITLE
Google script loading issue

### ISSUE THREAD

**Issue by prakashchokalingam** [MicroDroid/vue-invisible-recaptcha#1]
Most of the time am getting this alert issue otherwise this component is awesome

<img width="507" alt="screen shot 2017-07-19 at 7 15 29 pm" src="https://user-images.githubusercontent.com/5512765/28370258-6d92332e-6cb7-11e7-9f9b-ad0eb5986b57.png">

in console 

VM3220:1 Uncaught DOMException: Blocked a frame with origin "https://www.google.com" from accessing a cross-origin frame.
    at <anonymous>:1:15

**Comment by MicroDroid** [comment]
This is weird. Can you put this in a JSFiddle? The plugin works perfect for me, this only occurs when I have connection problems

**Comment by MicroDroid** [comment]
I'll close this given no response. If somebody gets this it's likely that they have some connectivity issue (or connection policy issue)
