### ISSUE TITLE
Uncaught Error: reCAPTCHA placeholder element must be an element or id

### ISSUE THREAD

**Issue by andrey-hohlov** [MicroDroid/vue-invisible-recaptcha#12]
If id prop not set recaptcha throws an error.
It happens because this._uid is number, but id can't be number.

I will create a pull request with a fix.

**Comment by MicroDroid** [comment]
I think `computedId` is meant to be in `computed` instead of `methods`?

**Comment by MicroDroid** [comment]
Fixed by #13
