### ISSUE TITLE
Conflicts with DevTools

### ISSUE THREAD

**Issue by dmitrybelyakov** [MicroDroid/vue-invisible-recaptcha#16]
As soon as we call `grecaptcha.render('...')` the app errors out saying `Uncaught TypeError: Cannot read property 'source' of null` pointing to some vue-devtools-proxy code. 

Disabling the vuejs devtools extension makes the error go away. 
Any idea what can be happening here and how to fix it?

Our test setup is quite minimal:

```js
import Vue from 'vue'
import Form from './components/auth/form'
new Vue({
    el: '#app',
    components: {
        'aform': Form,
    }
});
```
```js
<template>
    <div class="form">

        <invisible-recaptcha sitekey="6LdSW3MUAAAAMH5x0mi6Q8Ur8Sn7MAaz_4PCxxq" :validate="prepare" :callback="doSomething"
            class="btn btn-danger" type="submit" id="do-something-btn" :disabled="loading">
            Do something!
        </invisible-recaptcha>

    </div>
</template>

<script>
import Recaptcha from '../global/invisible-recaptcha'
export default {
    name: "login",
    components: {
        'invisible-recaptcha': Recaptcha,
    },
    data: function(){return {
        loading: false
    }},
    methods: {
        prepare: function(){
            console.log('PREPARE');
        },
        doSomething: function(){
            console.log('SUBMIT');
        }
    }
}
</script>

```

**Comment by dmitrybelyakov** [comment]
Don't mind this. Updating devtools helped! I'm gonna close this one. Cheers!

**Comment by dmitrybelyakov** [comment]
Sorry, actually it did not fix the issue. Restarting the browser makes it go away, but only until vue devtools are open. Happens both in Chrome and Firefox.

**Comment by dmitrybelyakov** [comment]
Ok, I believe this should be raised with vue devtools team. Closing!

**Comment by MicroDroid** [comment]
@dmitrybelyakov I'm not exactly sure what causes that. In fact, I had the same error show up when I was developing an Electron app even though I didn't use this plugin. I think it's some bug within vue-devtools itself, as you thought. It'd be interesting to open an issue as vue-devtools and reference it here.

Thanks for reporting the bug anyways <3

**Comment by dmitrybelyakov** [comment]
Heya, @MicroDroid!
No worries! I did some research on this yesterday and it's definitely devtools problem. They had some issues like that before with other libraries and components and those got fixed.  I did raise an issue with the vue-devtools team so hopefully this will get some attention: vuejs/vue-devtools#796

**Comment by MicroDroid** [comment]
Great! I'm going to put that issue on my watch list, just in case it turns out to be a bug within this library.

Actually, I presume this might be happening due to vue-invisible-recaptcha modifying DOM directly? Hmm.
