### ISSUE TITLE
"ref" is a reserved attribute and cannot be used as component prop.

### ISSUE THREAD

**Issue by imrefazekas** [MicroDroid/vue-invisible-recaptcha#5]
When I use as a component inside anothe component I see this error message on the console:
```
    "ref" is a reserved attribute and cannot be used as component prop.
```

**Comment by MicroDroid** [comment]
Please provide code.

**Comment by MicroDroid** [comment]
Due to no feedback provided, I will assume that the issue has been solved and it is not related to the library, given I have already done some testing regarding the `ref` feature which was recently added.

If you experience any further issues please leave a comment with example code here.
