### ISSUE TITLE
disables button and does nothing

### ISSUE THREAD

**Issue by pixelpaulaus** [MicroDroid/vue-invisible-recaptcha#9]
strange, i have it setup just like your example. but as soon as i click the button it runs the validation function, then the button gets disabled and nothing else is done.

**Comment by MicroDroid** [comment]
Can you please provide code?

Technically, the plugin disables the button only when Google's reCAPTCHA scripts are loading, and nothing else. So after you click the button, disabling the button has to do be done from an external function like the one supplied in `validate`

So I kinda believe you have something in there that disables the button and causes an issue. If you can please provide code I might be able to better help you.
